[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_twitter = "5w7wZhSYbd71GGsai2kbZUo3dKwCvf3Sv2mxFZ5nkVDA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/webclues/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
